#!/bin/sh
#

showError() {
  echo "Error: Attempt to commit changes that contain debug code"
  echo "Detected pattern for $1"
  echo "Line: $2"
  echo
  echo "If you know what you are doing you can disable this"
  echo "check using the following option:"
  echo 
  echo "  --no-verify "
  echo
  exit 1;
}

checkDiff() {
  LINE=`git diff --cached --unified=0 | grep "$1"`
  RT=$?
  
  if [ "$RT" = "0" ] ; then
    showError "$1" "$LINE"
  else
    echo "Check passed for $1"
  fi
}

checkDiff "debugger"
checkDiff "alert("
checkDiff "console.log"

# Run jslint on the files that are about to be committed.
# Be careful: the file in the working tree will be linted, not the files
# in the staging area.

for FILE in `git diff-index --name-only HEAD -- | egrep '*.js'`; do

	jslint --regexp --continue --nomen --plusplus --predef=define --bitwise --browser --vars --eqeq $FILE

	if [ $? -ne 0 ]; then
		echo "Commit aborted."
		echo ""
		echo "If you know what you are doing you can add an exclusion in .git/hooks/pre-commit"
		echo "or commit with --no-verify. But take care not to break the build."
		exit 1
	fi
done
