// Generated by CoffeeScript 1.3.3
(function() {
  var _ref;

  if (!((_ref = this.MathJax) != null ? _ref.Hub : void 0)) {
    if (typeof console !== "undefined" && console !== null) {
      console.error('MathJax did not load for some reason.');
    }
  }

  this.MathJax.Hub.Config({
    jax: ['input/MathML', 'input/TeX', 'input/AsciiMath', 'output/NativeMML', 'output/HTML-CSS'],
    extensions: ['asciimath2jax.js', 'tex2jax.js', 'mml2jax.js', 'MathMenu.js', 'MathZoom.js'],
    tex2jax: {
      inlineMath: [['[TEX_START]', '[TEX_END]'], ['\\(', '\\)']]
    },
    TeX: {
      extensions: ['AMSmath.js', 'AMSsymbols.js', 'noErrors.js', 'noUndefined.js'],
      noErrors: {
        disabled: true
      }
    },
    AsciiMath: {
      noErrors: {
        disabled: true
      }
    }
  });

}).call(this);
