// Generated by CoffeeScript 1.3.3
(function() {

  define(["aloha", "aloha/plugin", "ui/ui", '../../appmenu/appmenu', "i18n!format/nls/i18n", "i18n!aloha/nls/i18n", "PubSub", "ui/scopes", "css!simpletoolbar/css/simpletoolbar.css"], function(Aloha, Plugin, Ui, appmenu, i18n, i18nCore, PubSub, Scopes) {
    var CONTAINER_JQUERY;
    CONTAINER_JQUERY = jQuery('.toolbar');
    if (CONTAINER_JQUERY.length === 0) {
      CONTAINER_JQUERY = jQuery('<div></div>').addClass('toolbar-container').appendTo('body');
    }
    /*
       register the plugin with unique name
    */

    return Plugin.create("simpletoolbar", {
      defaultSettings: {
        'initfloat': false,
        'menu': [
          'saveButton', '', 'undo', 'redo', '', 'bold', 'italic', 'underline', 'superscript', 'subscript', '', 'unorderedList', 'orderedList', '', {
            text: 'Table',
            icon: 'aloha-table-insert',
            subMenu: ['createTable', '', 'addrowbefore', 'addrowafter', 'addcolumnbefore', 'addcolumnafter', '', 'deleterow', 'deletecolumn']
          }, {
            text: 'insertImage',
            icon: 'aloha-image-insert'
          }
        ],
        'dialogs': [
          {
            label: 'Image',
            scope: 'image',
            components: [["imageSource", "", "imageTitle", "", "imageAlt"], ["imageResizeWidth", "", "imageResizeHeight"], ["imageAlignLeft", "imageAlignRight", "imageAlignNone", "imageIncPadding", "", "imageCropButton", "imageCnrReset", "imageCnrRatio", "imageDecPadding"], ["imageBrowser"]]
          }
        ]
      },
      initDialogs: function(dialogMap, itemMap) {
        var d, dialog, gdiv, group, item, line, _i, _j, _k, _len, _len1, _len2, _ref, _ref1, _results;
        _ref = this.settings.dialogs;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          d = _ref[_i];
          dialog = Aloha.jQuery('<div />', {
            id: 'aloha-simpletoolbar-scope-' + d.scope
          });
          _ref1 = d.components;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            group = _ref1[_j];
            gdiv = Aloha.jQuery('<div class="aloha-simpletoolbar-dialog-group"/>');
            for (_k = 0, _len2 = group.length; _k < _len2; _k++) {
              line = group[_k];
              if (line.length === 0) {
                gdiv.append('<br />');
                continue;
              }
              item = Aloha.jQuery('<span />', {
                id: 'aloha-simpletoolbar-dialogitem-' + line
              });
              gdiv.append(item);
              itemMap[line] = item;
            }
            dialog.append(gdiv);
          }
          dialog.dialog({
            title: d.label,
            autoOpen: false,
            dialogClass: 'aloha',
            width: 'auto',
            close: function(event, ui) {
              return Scopes.setScope('Aloha.empty');
            }
          });
          _results.push(dialogMap[d.scope] = dialog);
        }
        return _results;
      },
      init: function() {
        var applyHeading, dialogItemLookup, dialogLookup, h, headingButtons, headingsButton, item, labels, order, plugin, recurse, toolbar, toolbarLookup, _i, _len, _ref;
        this.settings = jQuery.extend(true, this.defaultSettings, this.settings);
        window.toolbar = toolbar = new appmenu.ToolBar();
        toolbar.el.appendTo(CONTAINER_JQUERY);
        toolbar.el.addClass('aloha');
        toolbarLookup = {};
        recurse = function(item, lookupMap) {
          var icon, menuItem, subItem, subItems, subMenu;
          if ('string' === $.type(item)) {
            if ('' === item) {
              return new appmenu.Separator();
            }
            menuItem = new appmenu.ToolButton(item);
            lookupMap[item] = menuItem;
            return menuItem;
          } else {
            subItems = (function() {
              var _i, _len, _ref, _results;
              _ref = item.subMenu || [];
              _results = [];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                subItem = _ref[_i];
                _results.push(recurse(subItem, lookupMap));
              }
              return _results;
            })();
            icon = item.icon || null;
            if (subItems.length) {
              subMenu = new appmenu.Menu(subItems);
              menuItem = new appmenu.ToolButton(item.text, {
                subMenu: subMenu,
                iconCls: icon
              });
            } else {
              menuItem = new appmenu.ToolButton(item.text, {
                iconCls: icon
              });
              lookupMap[item.text] = menuItem;
            }
            return menuItem;
          }
        };
        _ref = this.settings.menu;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          toolbar.append(recurse(item, toolbarLookup));
        }
        dialogLookup = {};
        dialogItemLookup = {};
        this.initDialogs(dialogLookup, dialogItemLookup);
        Ui.__old_adopt = Ui.adopt;
        plugin = this;
        Ui.adopt = function(slot, type, settings) {
          var ItemRelay, Type, component;
          if (plugin.settings.initfloat) {
            try {
              Ui.__old_adopt(slot, type, settings);
            } catch (err) {

            }
          }
          ItemRelay = (function() {

            function ItemRelay(items) {
              this.items = items;
            }

            ItemRelay.prototype.show = function(bool) {
              var _j, _len1, _ref1, _results;
              if (bool == null) {
                bool = true;
              }
              _ref1 = this.items;
              _results = [];
              for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                item = _ref1[_j];
                _results.push(item.setHidden(!bool));
              }
              return _results;
            };

            ItemRelay.prototype.hide = function() {
              var _j, _len1, _ref1, _results;
              _ref1 = this.items;
              _results = [];
              for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                item = _ref1[_j];
                _results.push(item.setHidden(true));
              }
              return _results;
            };

            ItemRelay.prototype.setActive = function(bool) {
              var _j, _len1, _ref1, _results;
              _ref1 = this.items;
              _results = [];
              for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                item = _ref1[_j];
                _results.push(item.setChecked(bool));
              }
              return _results;
            };

            ItemRelay.prototype.setState = function(bool) {
              return this.setActive(bool);
            };

            ItemRelay.prototype.enable = function(bool) {
              var _j, _len1, _ref1, _results;
              if (bool == null) {
                bool = true;
              }
              _ref1 = this.items;
              _results = [];
              for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                item = _ref1[_j];
                _results.push(item.setDisabled(!bool));
              }
              return _results;
            };

            ItemRelay.prototype.disable = function() {
              var _j, _len1, _ref1, _results;
              _ref1 = this.items;
              _results = [];
              for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                item = _ref1[_j];
                _results.push(item.setDisabled(true));
              }
              return _results;
            };

            ItemRelay.prototype.setActiveButton = function(a, b) {
              return console.log("" + slot + " TODO:SETACTIVEBUTTON:", a, b);
            };

            ItemRelay.prototype.focus = function(a) {
              return console.log("" + slot + " TODO:FOCUS:", a);
            };

            ItemRelay.prototype.foreground = function(a) {
              return console.log("" + slot + " TODO:FOREGROUND:", a);
            };

            return ItemRelay;

          })();
          if (slot in toolbarLookup) {
            item = toolbarLookup[slot];
          } else if (slot in dialogItemLookup) {
            Type = settings ? type.extend(settings) : type;
            component = new Type();
            component.adoptParent(plugin);
            dialogItemLookup[slot].append(component.element);
            item = new appmenu.ToolButton('DUMMY_ITEM_THAT_SQUASHES_STATE_CHANGES');
          } else {
            item = new appmenu.ToolButton('DUMMY_ITEM_THAT_SQUASHES_STATE_CHANGES');
          }
          item.setText(settings.tooltip);
          item.setIcon(settings.icon);
          item.setAction(settings.click);
          if (settings["class"]) {
            item.addClass(settings["class"]);
          }
          item.element = item.el;
          return new ItemRelay([item]);
        };
        applyHeading = function(hTag) {
          return function() {
            var $newEl, $oldEl, rangeObject;
            rangeObject = Aloha.Selection.getRangeObject();
            if (rangeObject.isCollapsed()) {
              GENTICS.Utils.Dom.extendToWord(rangeObject);
            }
            Aloha.Selection.changeMarkupOnSelection(Aloha.jQuery("<" + hTag + "></" + hTag + ">"));
            $oldEl = Aloha.jQuery(rangeObject.getCommonAncestorContainer());
            $newEl = Aloha.jQuery(Aloha.Selection.getRangeObject().getCommonAncestorContainer());
            return $newEl.addClass($oldEl.attr('class'));
          };
        };
        order = ['p', 'h1', 'h2', 'h3'];
        labels = {
          'p': 'Normal Text',
          'h1': 'Heading Level 1',
          'h2': 'Heading Level 2',
          'h3': 'Heading Level 3'
        };
        headingButtons = (function() {
          var _j, _len1, _results;
          _results = [];
          for (_j = 0, _len1 = order.length; _j < _len1; _j++) {
            h = order[_j];
            _results.push(new appmenu.custom.Heading('<span class="menu-item">', labels[h], {
              action: applyHeading(h)
            }));
          }
          return _results;
        })();
        headingsButton = new appmenu.ToolButton("Heading 1", {
          subMenu: new appmenu.Menu(headingButtons)
        });
        toolbar.prepend(new appmenu.Separator());
        toolbar.prepend(headingsButton);
        Aloha.bind('aloha-editable-activated', function(e, params) {
          return toolbar.setAccelContainer(params.editable.obj);
        });
        Aloha.bind('aloha-editable-deactivated', function(e, params) {
          return toolbar.setAccelContainer();
        });
        Aloha.bind("aloha-selection-changed", function(event, rangeObject) {
          var $el, i, isActive, updated, _j, _len1;
          $el = Aloha.jQuery(rangeObject.startContainer);
          updated = false;
          for (i = _j = 0, _len1 = order.length; _j < _len1; i = ++_j) {
            h = order[i];
            isActive = $el.parents(h).length > 0;
            headingButtons[i].setChecked(isActive);
            if (isActive) {
              headingsButton.setText(labels[h]);
              updated = true;
            }
          }
          if (!updated) {
            return headingsButton.setText(labels['p']);
          }
        });
        plugin.openDialog = null;
        return PubSub.sub('aloha.ui.scope.change', function() {
          var d, scope, _j, _len1, _ref1;
          if (plugin.openDialog) {
            plugin.openDialog.dialog('close');
          }
          _ref1 = plugin.settings.dialogs;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            d = _ref1[_j];
            if (Scopes.isActiveScope(d.scope)) {
              plugin.openDialog = dialogLookup[d.scope];
              plugin.openDialog.dialog('open');
              break;
            }
          }
          scope = Scopes.getPrimaryScope();
          return console && console.log('Scope change to ' + scope);
        });
      },
      /*
           toString method
      */

      toString: function() {
        return "simpletoolbar";
      }
    });
  });

}).call(this);
