// Generated by CoffeeScript 1.3.3
(function() {

  define(['aloha', 'aloha/plugin', 'jquery', 'block/block', 'block/blockmanager', 'aloha/ephemera'], function(Aloha, Plugin, $, Block, BlockManager, Ephemera) {
    Ephemera.classes('aloha-block', 'aloha-block-handle', 'aloha-block-TitleBlock', 'aloha-block-active', 'aloha-block-highlighted');
    Ephemera.attributes('data-aloha-block-type', 'contenteditable');
    return Plugin.create("title", {
      init: function() {
        var TitleBlock, emap;
        TitleBlock = Block.AbstractBlock.extend({
          title: 'Title',
          init: function($element, postProcessFn) {
            $element.wrapInner('<div class="title-editor document_title aloha-editable" />');
            return postProcessFn();
          },
          update: function($element, postProcessFn) {
            return postProcessFn();
          },
          renderBlockHandlesIfNeeded: function() {}
        });
        BlockManager.registerBlockType('TitleBlock', TitleBlock);
        emap = Ephemera.ephemera().pruneFns.push(function(node) {
          var $node;
          $node = $(node);
          if ($node.is('div.title')) {
            $node.text($node.find('.title-editor').text());
            return $node.get(0);
          }
          return node;
        });
        return Aloha.bind('aloha-editable-created', function($event, editable) {
          editable.obj.find('div.title:not(.aloha-block)').alohaBlock({
            'aloha-block-type': 'TitleBlock'
          });
          if (editable.obj.is('.title-editor')) {
            return editable.obj.off('keydown').on('keydown', null, 'return', function(e) {
              var $p, range;
              e.preventDefault();
              $p = $('<p><br /></p>');
              editable.obj.parent().after($p);
              range = new GENTICS.Utils.RangeObject();
              range.startContainer = range.endContainer = $p[0];
              range.startOffset = range.endOffset = 0;
              range.select();
              return false;
            });
          }
        });
      },
      toString: function() {
        return "title";
      }
    });
  });

}).call(this);
