// Generated by CoffeeScript 1.3.3
(function() {

  define(["aloha", "aloha/plugin", "ui/ui", "i18n!format/nls/i18n", "i18n!aloha/nls/i18n", "aloha/console", "css!toolbar/css/toolbar.css"], function(Aloha, Plugin, Ui, i18n, i18nCore) {
    var CONTAINER_JQUERY, makeItemRelay;
    CONTAINER_JQUERY = jQuery('.toolbar');
    if (CONTAINER_JQUERY.length === 0) {
      CONTAINER_JQUERY = jQuery('<div></div>').addClass('toolbar-container aloha').appendTo('body');
    }
    makeItemRelay = function(slot, $buttons) {
      var ItemRelay;
      ItemRelay = (function() {

        function ItemRelay() {}

        ItemRelay.prototype.show = function() {
          return $buttons.removeClass('hidden');
        };

        ItemRelay.prototype.hide = function() {};

        ItemRelay.prototype.setActive = function(bool) {
          if (!bool) {
            $buttons.removeClass('active');
          }
          if (bool) {
            return $buttons.addClass('active');
          }
        };

        ItemRelay.prototype.setState = function(bool) {
          return this.setActive(bool);
        };

        ItemRelay.prototype.enable = function(bool) {
          if (bool == null) {
            bool = true;
          }
          if ($buttons.is('.btn')) {
            if (!bool) {
              $buttons.attr('disabled', 'disabled');
            }
            if (bool) {
              return $buttons.attr('disabled', null);
            }
          } else {
            if (!bool) {
              $buttons.parent().addClass('disabled');
            }
            if (bool) {
              return $buttons.parent().removeClass('disabled');
            }
          }
        };

        ItemRelay.prototype.disable = function() {
          return this.enable(false);
        };

        ItemRelay.prototype.setActiveButton = function(a, b) {
          return console.log("" + slot + " TODO:SETACTIVEBUTTON:", a, b);
        };

        ItemRelay.prototype.focus = function(a) {
          return console.log("" + slot + " TODO:FOCUS:", a);
        };

        ItemRelay.prototype.foreground = function(a) {
          return console.log("" + slot + " TODO:FOREGROUND:", a);
        };

        return ItemRelay;

      })();
      return new ItemRelay();
    };
    /*
       register the plugin with unique name
    */

    return Plugin.create("toolbar", {
      init: function() {
        var changeHeading, headings, squirreledEditable;
        squirreledEditable = null;
        CONTAINER_JQUERY.find('.action').addClass('disabled missing-a-click-event').on('click', function(evt) {
          return evt.preventDefault();
        });
        CONTAINER_JQUERY.find('a.action').parent().addClass('disabled missing-a-click-event').on('click', function(evt) {
          return evt.preventDefault();
        });
        Ui.adopt = function(slot, type, settings) {
          var $buttons;
          $buttons = CONTAINER_JQUERY.find(".action." + slot);
          $buttons.add($buttons.parent()).removeClass('disabled missing-a-click-event');
          $buttons.off('click');
          $buttons.on('click', function(evt) {
            evt.preventDefault();
            Aloha.activeEditable = Aloha.activeEditable || squirreledEditable;
            this.element = this;
            return settings.click.bind(this)(evt);
          });
          return makeItemRelay(slot, $buttons);
        };
        changeHeading = function(evt) {
          var $el, $newEl, $oldEl, hTag, rangeObject;
          $el = jQuery(this);
          hTag = $el.attr('data-tagname');
          rangeObject = Aloha.Selection.getRangeObject();
          if (rangeObject.isCollapsed()) {
            GENTICS.Utils.Dom.extendToWord(rangeObject);
          }
          Aloha.Selection.changeMarkupOnSelection(Aloha.jQuery("<" + hTag + "></" + hTag + ">"));
          $oldEl = Aloha.jQuery(rangeObject.getCommonAncestorContainer());
          $newEl = Aloha.jQuery(Aloha.Selection.getRangeObject().getCommonAncestorContainer());
          $newEl.addClass($oldEl.attr('class'));
          return evt.preventDefault();
        };
        headings = CONTAINER_JQUERY.find(".changeHeading");
        headings.on('click', changeHeading);
        headings.add(headings.parent()).removeClass('disabled missing-a-click-event');
        Aloha.bind('aloha-editable-activated', function(event, data) {
          return squirreledEditable = data.editable;
        });
        return Aloha.bind("aloha-selection-changed", function(event, rangeObject) {
          var $el, currentHeading;
          $el = Aloha.jQuery(rangeObject.startContainer);
          currentHeading = CONTAINER_JQUERY.find('.currentHeading');
          currentHeading.text(headings.first().text());
          currentHeading.on('click', function(evt) {
            return evt.preventDefault();
          });
          return headings.each(function() {
            var heading, selector;
            heading = jQuery(this);
            selector = heading.attr('data-tagname');
            if (selector && $el.parents(selector)[0]) {
              return currentHeading.text(heading.text());
            }
          });
        });
      },
      /*
           toString method
      */

      toString: function() {
        return "toolbar";
      }
    });
  });

}).call(this);
