// Generated by CoffeeScript 1.3.3
(function() {

  define(['aloha', 'jquery', 'aloha/console'], function(Aloha, jQuery, console) {
    var filter, populator, selector;
    selector = 'figure';
    filter = function() {
      return this.nodeName.toLowerCase() === 'figure' || jQuery(this).parents('figure')[0];
    };
    populator = function($bubble) {
      var $button, $el, separator;
      $el = this;
      if ($el.children('.title')[0]) {
        $button = jQuery('<a href="javascript:void">Remove Title</a>');
        $button.on('mousedown', function() {
          return $el.children('.title').remove();
        });
        $bubble.append($button);
      } else {
        $button = jQuery('<a href="javascript:void">Add Title</a>');
        $button.on('mousedown', function() {
          var newTitle;
          newTitle = jQuery('<div class="title aloha-optional aloha-empty">Insert Title Here</div>');
          return $el.prepend(newTitle);
        });
        $bubble.append($button);
      }
      separator = jQuery('<span class="separator"> | </span>');
      $bubble.append(separator);
      if ($el.children('figcaption')[0]) {
        $button = jQuery('<a href="javascript:void">Remove Caption</a>');
        $button.on('mousedown', function() {
          return $el.children('figcaption').remove();
        });
        return $bubble.append($button);
      } else {
        $button = jQuery('<a href="javascript:void">Add Caption</a>');
        $button.on('mousedown', function() {
          var newCaption;
          newCaption = jQuery('<figcaption class="aloha-optional aloha-empty">Insert Caption Here</figcaption>');
          return $el.append(newCaption);
        });
        return $bubble.append($button);
      }
    };
    return {
      selector: selector,
      populator: populator,
      filter: filter
    };
  });

}).call(this);
