if (typeof GENTICS_Aloha_base == 'undefined') {
	GENTICS_Aloha_base = '/Aloha/';
}

document.write('<script type="text/javascript" src="/Aloha/deps/jquery-1.4.2.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/deps/jquery.json-2.2.min.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/deps/jquery.getUrlParam.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/deps/jquery.cookie.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/deps/extjs/ext-jquery-adapter-debug.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/deps/extjs/ext-foundation-debug.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/deps/extjs/cmp-foundation-debug.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/deps/extjs/ext-dd-debug.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/deps/extjs/window-debug.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/deps/extjs/pkg-buttons-debug.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/deps/extjs/pkg-tabs-debug.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/deps/extjs/pkg-tips-debug.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/deps/extjs/pkg-toolbars-debug.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/deps/extjs/pkg-menu-debug.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/utils/jquery.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/utils/lang.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/utils/range.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/utils/nodeinfo.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/utils/position.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/core.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/ui.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/css.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/editable.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/ribbon.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/event.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/floatingmenu.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/ierange-m2.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/jquery.aloha.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/log.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/markup.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/message.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/plugin.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/selection.js"></script>');
document.write('<script type="text/javascript" src="/Aloha/core/sidebar.js"></script>');
